version: '3.7'
services:
  switch_commander:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb_container
    networks:
      - backend
  
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume
    networks:
      - backend

  mssql_data_container:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Wambo1234"
    ports:
      - "1433:1433"
    volumes:
      - mssql_volume:/var/opt/mssql
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb_volume:
  mssql_volume:
