FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["SwitchCommander.WebAPI/SwitchCommander.WebAPI.csproj", "SwitchCommander.WebAPI/"]
RUN dotnet restore "SwitchCommander.WebAPI/SwitchCommander.WebAPI.csproj"
COPY . .
WORKDIR "/src/SwitchCommander.WebAPI"
RUN dotnet build "SwitchCommander.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SwitchCommander.WebAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SwitchCommander.WebAPI.dll"]
