name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore Dependencies
      run: dotnet restore

    - name: Build SwitchCommander.Application
      run: dotnet build --configuration Release --project SwitchCommander.Application/SwitchCommander.Application.csproj

    - name: Build SwitchCommander.Domain
      run: dotnet build --configuration Release --project SwitchCommander.Domain/SwitchCommander.Domain.csproj

    # Exclude the SwitchCommander.WPF project from the build process
    - name: Skip SwitchCommander.WPF Project
      run: echo "Skipping SwitchCommander.WPF project"
